apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-prediction
  labels:
    app: diabetes-prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diabetes-prediction
  template:
    metadata:
      labels:
        app: diabetes-prediction
    spec:
      containers:
      - name: diabetes-prediction
        image: arpitpattani/mlops-diabetic-prediction:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-prediction-service
spec:
  selector:
    app: diabetes-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
